version: '3.8'

services:
  gradio-app:
    build:
      context: ./deployment
      dockerfile: gradio.Dockerfile
    ports:
      - "7860:7860"
    volumes:
      - ./deployment:/app
    command: bash -c "python gradio_app.py"